# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QAction, qApp, QApplication
import sys

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 370)
        #MainWindow.setStyleSheet("#MainWindow{border-image:url(timg_meitu_1.jpg)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(110, 200, 131, 41))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(420, 200, 131, 41))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(160, 80, 361, 41))
        self.title.setAlignment(QtCore.Qt.AlignCenter)   #设置居中
        self.title.setObjectName("title")
        self.desgin = QtWidgets.QLabel(self.centralwidget)
        self.desgin.setGeometry(QtCore.QRect(280, 320, 111, 21))
        self.desgin.setAlignment(QtCore.Qt.AlignCenter)   #设置居中
        self.desgin.setObjectName("desgin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 673, 26))
        self.menuBar.setObjectName("menuBar")
        #self.menu = QtWidgets.QMenu(self.menuBar)
        #self.menu.setObjectName("menu")
        self.menug = QtWidgets.QMenu(self.menuBar)
        self.menug.setObjectName("menug")
        MainWindow.setMenuBar(self.menuBar)
        #self.menuBar.addAction(self.menu.menuAction())

        #设置目标栏按钮
        self.localfile = QtWidgets.QMenu(self.menuBar)
        self.localfile.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.localfile.setToolTipDuration(5)
        self.localfile.setToolTipsVisible(False)
        self.localfile.setObjectName("localfile")
        self.localfile_action = QAction('&关于', self)
        self.localfile_action.setCheckable(False)
        self.localfile_action.setObjectName('localFileAction')




        self.menuBar.addAction(self.localfile_action)




        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网易云评论爬取词云生成器"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#ffaa00;\">网易云评论爬取词云生成器</span></p></body></html>"))
        self.desgin.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">power by leaf</span></p><p><br/></p></body></html>"))
        #self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menug.setTitle(_translate("MainWindow", "关于"))

    def use_palette(self):
        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(),  QtGui.QBrush(QtGui.QPixmap("E://PycharmProjects//Pybasic//Pic//background2.jpg")))
        self.setPalette(window_pale)
