# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finally.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Final_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 200)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_Button = QtWidgets.QPushButton(self.centralwidget)
        self.open_Button.setGeometry(QtCore.QRect(30, 140, 81, 31))
        self.open_Button.setObjectName("open_Button")
        self.back_Button = QtWidgets.QPushButton(self.centralwidget)
        self.back_Button.setGeometry(QtCore.QRect(210, 140, 81, 31))
        self.back_Button.setObjectName("back_Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 70, 141, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网易云评论爬取词云生成器"))
        self.open_Button.setText(_translate("MainWindow", "打开图片"))
        self.back_Button.setText(_translate("MainWindow", "关闭"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">已生成词云!!</span></p></body></html>"))

    def use_palette(self):
        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(),  QtGui.QBrush(QtGui.QPixmap("E://PycharmProjects//Pybasic//Pic//background5.jpg")))
        self.setPalette(window_pale)