# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handle.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction

class Ui_HandleWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.desgin = QtWidgets.QLabel(self.centralwidget)
        self.desgin.setGeometry(QtCore.QRect(280, 320, 111, 21))
        self.desgin.setObjectName("desgin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 110, 321, 81))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 673, 26))
        self.menuBar.setObjectName("menuBar")
        #self.menu = QtWidgets.QMenu(self.menuBar)
        #self.menu.setObjectName("menu")
        self.menug = QtWidgets.QMenu(self.menuBar)
        self.menug.setObjectName("menug")
        MainWindow.setMenuBar(self.menuBar)
        #self.menuBar.addAction(self.menu.menuAction())

        #设置目标栏按钮
        self.localfile = QtWidgets.QMenu(self.menuBar)
        self.localfile.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.localfile.setToolTipDuration(5)
        self.localfile.setToolTipsVisible(False)
        self.localfile.setObjectName("localfile")
        self.localfile_action = QAction('&关于', self)
        self.localfile_action.setCheckable(False)
        self.localfile_action.setObjectName('localFileAction')
        self.menuBar.addAction(self.localfile_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网易云评论爬取词云生成器"))
        self.desgin.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">power by leaf</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">正在爬取中，请稍后。。。</span></p></body></html>"))
        self.menug.setTitle(_translate("MainWindow", "关于"))

    def use_palette(self):
        #self.setWindowTitle("设置背景图片")
        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(),  QtGui.QBrush(QtGui.QPixmap("E://PycharmProjects//Pybasic//Pic//background4.jpg")))
        self.setPalette(window_pale)