# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type_sn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Song_Window(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 181)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 60, 271, 41))
        self.label.setObjectName("label")
        self.close_Button = QtWidgets.QPushButton(Dialog)
        self.close_Button.setGeometry(QtCore.QRect(250, 140, 93, 28))
        self.close_Button.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "这是一个弹框"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">请输入歌曲名！！！！</span></p></body></html>"))
        self.close_Button.setText(_translate("Dialog", "确定"))
