# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QAction, qApp, QApplication

class Ui_SecondWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 370)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(100, 180, 131, 41))
        self.pushButton_next.setObjectName("pushButton_exit")
        self.desgin = QtWidgets.QLabel(self.centralwidget)
        self.desgin.setGeometry(QtCore.QRect(280, 320, 111, 21))
        self.desgin.setObjectName("desgin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 70, 191, 31))
        self.label.setObjectName("label")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(440, 180, 131, 41))
        self.pushButton_back.setObjectName("pushButton_exit_2")
        # self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        # self.textEdit.setGeometry(QtCore.QRect(300, 60, 261, 41))
        # self.textEdit.setObjectName("textEdit")
        self.lineEdit_song = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_song.setObjectName("lineEdit_song")
        self.lineEdit_song.setGeometry(QtCore.QRect(300, 60, 261, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 673, 26))
        self.menuBar.setObjectName("menuBar")
        #self.menu = QtWidgets.QMenu(self.menuBar)
        #self.menu.setObjectName("menu")
        self.menug = QtWidgets.QMenu(self.menuBar)
        self.menug.setObjectName("menug")
        MainWindow.setMenuBar(self.menuBar)
        #self.menuBar.addAction(self.menu.menuAction())

        #设置目标栏按钮
        self.localfile = QtWidgets.QMenu(self.menuBar)
        self.localfile.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.localfile.setToolTipDuration(5)
        self.localfile.setToolTipsVisible(False)
        self.localfile.setObjectName("localfile")
        self.localfile_action = QAction('&关于', self)
        self.localfile_action.setCheckable(False)
        self.localfile_action.setObjectName('localFileAction')
        self.menuBar.addAction(self.localfile_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网易云评论爬取词云生成器"))
        self.pushButton_next.setText(_translate("MainWindow", "确定"))
        self.desgin.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" \">power by leaf</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:15pt; font-weight:bold; \">请输入歌曲名称：</span></p></body></html>"))
        self.pushButton_back.setText(_translate("MainWindow", "返回"))
        #self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menug.setTitle(_translate("MainWindow", "关于"))

    def use_palette(self):
        window_pale = QtGui.QPalette()
        window_pale.setBrush(self.backgroundRole(),  QtGui.QBrush(QtGui.QPixmap("E://PycharmProjects//Pybasic//Pic//background3.jpg")))
        self.setPalette(window_pale)